### ISSUE TITLE
[BUG] Incompatible with Magnesium (and protentially, Magnesium Extras too)

### ISSUE THREAD

**Issue by baalphamquoc** [MundM2007/Ultimate-Progression#23]
**Describe the bug**
Creating a new world and/or joining a world will result in a crash in Minecraft

**To Reproduce**
1. Install (or add) Magnesium with/without Magnesium extras
2. Create a new world, or play an already created world
3. Crash will happen at the end of the joining world stage - you can unpause the game and immediately followed up by a crash

**Expected behavior**
A crash is guaranteed at the Joining World stage of loading.

**Versions (please complete the following information):**
- Modpack version: 0.6.5
- Server?: No

**Additional context**
Tested with various degrees - Magnesium + barebone pack / Magnesium + Extra + barebone pack / barebone pack

**Comment by MundM2007** [comment]
Pleased don't add mods to my modpack, espacially if thier Performance Mods. This could lead to Crashes (what happened here), i will Not allways fix These and can't always do something about it.  Though if you want me to help you i need atleast a crashlog. If you added These mods because of Low fps disable mipmapping and try optifine First.
